### PR TITLE
Feature/support typescript

### LINKED ISSUE #1: Support for TypeScript
Hi,

On a project I'm currently working on, we faced a migration from common JS to TypeScript. We also use your library, however it does not support TypeScript.

I am opening this issue to improve this package. I also offer my contribution to solving this.

### PR DESCRIPTION
**Pull request by IgorBezanovic**
For a more detailed TypeScript declaration, it is necessary to add JSDoc to the JavaScript code, for example:
```
/**
 * Function check the range
 *
 * @param {number} start
 * @param {number} end
 *
 * @return {Array<number>} rangeResult
 */
function range(start, end) {
  var rangeResult = [];
  for (var i = start; i < end; i++) {
    rangeResult.push(i);
  }
  return rangeResult;
}
```

With this added code, TypeScript is supported but every variable and return value is ANY.
Before publishing the library, it is necessary to execute the command:
`npm run build:types`
Also bump-up version of package

### CODE REVIEW

**Comment by SVasilev** [comment]
Hey there! Thanks for the PR!
Have you forgotten to add the JSDocs to the functions or is it unnecessary in your opinion?

**Comment by IgorBezanovic** [comment]
It's pleasure!

I did not forget, as I wrote above, we need to add them, however, since it is your library, I believe that it will be much easier for you to add JSDocs, because you already fully know what the function does and what the input parameters are, I also believe that you also know what the output of each function is.

My opinion is that JSDocs should be added under mandatory because that is the only way we ensure proper functioning.

We can communicate if you send me a description of the functionality, what they do, what is input and output, so I would add it to the PR, or if you add it, maybe it's a quick action if you add it?

**Comment by SVasilev** [comment]
Hey,
As you've probably guessed, I haven't used JS for the last 8 years. You will know what these functions do better than me 😃 
If you are willing to do your best at documenting the code - give it a go. If not - I can merge it as is.

Regarding this:
> Before publishing the library, it is necessary to execute the command:
npm run build:types

I don't have a Node environment so I guess I should install one and run this command in the root of the project, right?

**Comment by IgorBezanovic** [comment]
Hi,

I just added JSDocs. Now if you agree you can merge to master.
Next is the regular procedure, to raise the version of the library, generate types and publish library 🚀

**Pull request merged**
